#端口配置
server:
  port: 80
#数据库连接配置
spring:
  datasource:
    druid:
     # driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: org.postgresql.Driver
     # url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      url: jdbc:postgresql://localhost:5432/manage?useUnicode=true&characterEncoding=UTF-8
      username: postgres
      password: 654321
      db-type: com.alibaba.druid.pool.DruidDataSource
      # 下面为druid连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20

      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,slf4j,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

#mybatis配置
mybatis:
  type-aliases-package: com.ed.pojo

